validates:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  micropost:
    max_length: 140
image:
  default:
    size: 80
  avatar:
    size: 50
pagy:
  size: 10
email:
  from: "noreply.sampleapp.test@gmail.com"
password_reset:
  expire_time: 2
minipost:
  accept_path: "image/jpeg,image/gif,image/png"
  resize_to_limit: [500, 500]
  image_size: 5
