validates:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
image:
  default:
    size: 80
  avatar:
    size: 50
pagy:
  size: 10
email:
  from: "noreply.sampleapp.test@gmail.com"
